"""empty message

Revision ID: 12bf408171bf
Revises: c3db3057e3ad
Create Date: 2023-03-28 14:13:52.140629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12bf408171bf'
down_revision = 'c3db3057e3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_attachment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_attachment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='comment_attachment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
