"""empty message

Revision ID: 591f85c18b36
Revises: 12bf408171bf
Create Date: 2023-04-01 17:04:42.194413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '591f85c18b36'
down_revision = '12bf408171bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('lesson', 'content')
    op.drop_column('lesson', 'video_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('lesson', sa.Column('content', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('lesson', 'description')
    # ### end Alembic commands ###
