"""empty message

Revision ID: 928d93a86859
Revises: 
Create Date: 2023-03-24 22:10:37.908719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928d93a86859'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
