"""empty message

Revision ID: c3db3057e3ad
Revises: f209a8e1a7de
Create Date: 2023-03-28 14:12:10.195334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3db3057e3ad'
down_revision = 'f209a8e1a7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('attachment_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'attachment_url')
    # ### end Alembic commands ###
