"""empty message

Revision ID: e7e9368ba4a3
Revises: 928d93a86859
Create Date: 2023-03-25 11:10:25.903382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7e9368ba4a3'
down_revision = '928d93a86859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=200), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
