version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: "host"
    volumes:
      - ./conf:/etc/nginx
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html


