version: '2.17'
services:
  db:
    image: mysql:5.7.41-debian
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./mysql-data:/var/lib/mysql

